name: Comment on issue

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DORAS_ADMIN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Thank you for making Doras a better place 🚀**
              
              This has been added to our [Public Project Board](https://github.com/orgs/dorasto/projects/11/) and our team will triage and action accordingly.'
            })
