name: Milestone Creator
on:
  workflow_dispatch:
    inputs:
      milestone_name:
        description: 'Milestone Version'
        required: true

jobs:
  create-milestone-and-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DORAS_ADMIN }}
          script: |
            // Create the milestone
            const milestone = await github.rest.issues.createMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: context.payload.inputs.milestone_name
            });
            
            // Create an issue with the same name and link it to the milestone
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: context.payload.inputs.milestone_name,
              milestone: milestone.data.number,
              body: `Issue created for milestone: ${context.payload.inputs.milestone_name}`
            });
